server:
  port: 9010
spring:
  application:
   ##name必须一样，不然高可用会导致unavailable-replicas
    name: mss-eureka
eureka:
  instance:
    hostname: mss-eureka1
  client:
    ##这里要覆盖application的设置，不然会读取application文件导致unavailable-replicas
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://mss-eureka1:9011/eureka/
  server:
    #### 清理间隔（单位毫秒，默认是60*1000），开发环境设置如下可快速移除不可用的服务
      eviction-interval-timer-in-ms: 5000
      enable-self-preservation: false

###actuator监控点 start####
endpoints:
  health:
    sensitive: false
    enabled: true
##默认情况下很多端点是不允许访问的，会返回401:Unauthorized
management:
  security:
    enabled: false
###actuator监控点 end####