server:
  port: 9021
spring:
  application:
    name: mss-upms
  datasource:
      url: jdbc:mysql://bdm248315460.my3w.com:3306/bdm248315460_db
      username: bdm248315460
      password: disvenk472810
      druid:
        driver-class-name: com.mysql.jdbc.Driver
mapper:
  mappers:
     com.microservice.skeleton.upms.mapper
eureka:
  instance:
    prefer-ip-address: true #使用IP注册
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
    ##续约更新时间间隔设置5秒，m默认30s
    lease-renewal-interval-in-seconds: 5
    ##续约到期时间10秒，默认是90秒
    lease-expiration-duration-in-seconds: 10
  client:
      service-url:
        defaultZone: http://mss-eureka1:9010/eureka/